# Generated by Django 5.0.6 on 2025-01-13 12:55

from django.db import migrations

def create_tiles_for_map(apps, map_id, grid_size, next_map_portal_tile_coords=None):
    Tile = apps.get_model('api', 'Tile')
    Map = apps.get_model('api', 'Map')
    map = Map.objects.get(pk=map_id)

    # Créer les tuiles
    tiles = {}
    for x in range(grid_size):
        for y in range(grid_size):
            tile = Tile.objects.create(map=map, posX=x, posY=y)
            tiles[(x, y)] = tile
            
          # Set portal if specified and coordinates match
            if next_map_portal_tile_coords and (x, y) == next_map_portal_tile_coords:
                try:
                    next_map = Map.objects.get(pk=map.id + 1)
                    tile.portal_to_map = next_map
                except Map.DoesNotExist:
                    pass  # No next map, so ignore portal

            tile.save()

    # Connecter les tuiles horizontalement et verticalement
    for y in range(grid_size):
        for x in range(grid_size):
            tile = tiles[(x, y)]
            if y < grid_size - 1:
                tile.east_door = tiles[(x, y + 1)]
            if x < grid_size - 1:
                tile.south_door = tiles[(x + 1, y)]
            if y > 0:
                tile.west_door = tiles[(x, y - 1)]
            if x > 0:
                tile.north_door = tiles[(x - 1, y)]
            tile.save()

def add_initial_data(apps, schema_editor):
    Map = apps.get_model('api', 'Map')
    CharacterClass = apps.get_model('api', 'CharacterClass')
    Tile = apps.get_model('api', 'Tile')
    Skill = apps.get_model('api', 'Skill')
    NPC = apps.get_model('api', 'NPC')
    Item = apps.get_model('api', 'Item')
    Shop = apps.get_model('api', 'Shop')
    ShopItem = apps.get_model('api', 'ShopItem')

    # Création de mondes
    map1a = Map.objects.create(name='Land of the Ancients', description='A mysterious world filled with ancient magic.', starting_map=True)
    map2a = Map.objects.create(name='Dragon Kingdom', description='A kingdom where dragons rule supreme.')
    map3a = Map.objects.create(name='Whispering Wilds', description='An untamed expanse of primal forests teeming with life and hidden dangers.')
    map4a = Map.objects.create(name='Sunken City of Stars', description='A submerged metropolis, bathed in an ethereal glow, where forgotten technology hums beneath the waves.')

    map1b = Map.objects.create(name='The Abyss', description='A dark and foreboding realm where unspeakable horrors lurk.', starting_map=True)

    # Création de classes de personnages
    characterclass1 = CharacterClass.objects.create(name='Warrior', description='The warrior stands as a paragon of strength and defense. With Heroic Strike to unleash powerful attacks and Shield Bash to disrupt and stun enemies, they dominate the battlefield with unwavering might and tactical prowess.')
    characterclass2 = CharacterClass.objects.create(name='Mage', description='The mage wields the forces of fire and ice with unmatched skill. Casting Fireball to engulf foes in flames and Ice Bolt to chill them to the core, they dominate the battlefield with elemental fury. They summon storms that terrify enemies.')
    characterclass3 = CharacterClass.objects.create(name='Hunter', description='In the many worlds of the game, the hunter is a master of precise and devastating shots. With his Aimed Shot for targeted strikes and Multi-Shot to hit multiple enemies at once, he dominates the battlefield with lethal precision.')
    characterclass4 = CharacterClass.objects.create(name='Rogue', description='The rogue excels in stealth and precision. Using Backstab to deliver lethal strikes from the shadows and Gouge to incapacitate foes momentarily, they control the flow of combat with cunning and agility.')
    characterclass5 = CharacterClass.objects.create(name='Priest', description='The Priest is a master of restorative and radiant magic. With his Heal spell for restoring health and Holy Light to smite enemies with divine power, he supports allies and vanquishes foes with unparalleled brilliance.')

    # Créer des tuiles pour chaque monde
    create_tiles_for_map(apps, map1a.id, 3, next_map_portal_tile_coords=(2, 1))
    create_tiles_for_map(apps, map2a.id, 5, next_map_portal_tile_coords=(4, 0))
    create_tiles_for_map(apps, map3a.id, 10, next_map_portal_tile_coords=(9, 4))
    create_tiles_for_map(apps, map4a.id, 4)

    create_tiles_for_map(apps, map1b.id, 3)

    # Création de compétences
    descriptions = {
        'Heroic Strike': 'A powerful melee attack that deals significant damage to a single target.',
        'Shield Bash': 'A stunning blow that interrupts the target\'s actions and knocks them back.',
        'Fireball': 'A projectile that hurls a ball of fire at the target, dealing damage and igniting them.',
        'Ice Bolt': 'A projectile that hurls a bolt of ice at the target, dealing damage and slowing them.',
        'Backstab': 'A sneak attack that deals bonus damage if the target is facing away from the rogue.',
        'Gouge': 'A quick strike that stuns the target for a short duration.',
        'Aimed Shot': 'A precise shot that deals high damage to a single target.',
        'Multi-Shot': 'A rapid-fire attack that deals damage to multiple targets.',
        'Heal': 'A spell that restores health to a target.',
        'Holy Light': 'A powerful healing spell that also dispels harmful effects from the target.',
    }
    
    for skill_name, skill_description in descriptions.items():
        Skill.objects.create(name=skill_name, description=skill_description)

    # Création de monstres
    monster1 = NPC.objects.create(
        name='Skeleton Warrior',
        hp=1,
        tile=Tile.objects.get(map=map1a, posX=1, posY=0),
        species='Undead',
        role='Enemy',
        behaviour='Hostile',
        attack_power=1,
        defense=2,
        experience=20,
    )

    monster2 = NPC.objects.create(
        name='Goblin Thief',
        hp=5,
        tile=Tile.objects.get(map=map1a, posX=2, posY=0),
        species='Goblin',
        role='Enemy',
        behaviour='Hostile',
        attack_power=2,
        defense=1,
        experience=30,
    )

    monster3 = NPC.objects.create(
        name='Red Slime',
        hp=3,
        tile=Tile.objects.get(map=map1a, posX=2, posY=1),
        species='Beast',
        role='Enemy',
        behaviour='Hostile',
        attack_power=1,
        defense=0,
        experience=15,
    )

    monster4 = NPC.objects.create(
        name='Fire Dragon',
        hp=100,
        tile=Tile.objects.get(map=map2a, posX=4, posY=3),
        species='Dragon',
        role='Boss',
        behaviour='Hostile',
        attack_power=30,
        defense=10,
        experience=100,
    )

    # Création d'objets
    sword = Item.objects.create(
        name='Iron Sword',
        item_type='Weapon',
        description='A basic iron sword for beginners.',
        attack_power = 1,
    )

    potion = Item.objects.create(
        name='Healing Potion',
        item_type='Potion',
        description='Restores health when consumed.',
        healing=10,    
        )

    # Création de magasins
    alchemy_shop = Shop.objects.create(
        name='Alchemy Shop',
        tile=Tile.objects.get(map=map1a, posX=0, posY=2),
    )
    ShopItem.objects.create(shop=alchemy_shop, item=potion, price=15)

    equipment_shop = Shop.objects.create(
        name='Starforge Armory',
        tile=Tile.objects.get(map=map2a, posX=1, posY=3),
    )
    armor = Item.objects.create(
        name='Steel Armor',
        item_type='Equipment',
        description='Provides excellent protection in battle.',
        defense=10,
    )
    ShopItem.objects.create(shop=equipment_shop, item=armor, price=100)

    food_shop = Shop.objects.create(
        name='Enchanted Bakery',
        tile=Tile.objects.get(map=map3a, posX=4, posY=2),
    )
    bread = Item.objects.create(
        name='Loaf of Enchanted Bread',
        item_type='Food',
        description='Restores a small amount of health and boosts energy.',
        healing=2,
        )
    ShopItem.objects.create(shop=food_shop, item=bread, price=5)

    manuscript_shop = Shop.objects.create(
        name='Arcane Archives',
        tile=Tile.objects.get(map=map4a, posX=2, posY=1),
    )
    scroll = Item.objects.create(
        name='Scroll of Knowledge',
        item_type='Manuscript',
        description='Contains ancient wisdom. Can be used to learn new skills.',
        )
    ShopItem.objects.create(shop=manuscript_shop, item=scroll, price=50)

    # Ajout d'objets au coffre
    golden_amulet = Item.objects.create(
        name='Golden Amulet',
        item_type='Equipment',
        description='Enhances magical abilities.',
        
        )
    starlight_gem = Item.objects.create(
        name='Starlight Gem',
        item_type='Gem',
        description='Radiant gemstone that glows softly.',

    )
    scroll_of_wisdom = Item.objects.create(
        name='Scroll of Ancient Wisdom',
        item_type='Manuscript',
        description='Reveals forgotten spells and arcane knowledge.',
        
    )

    dragon_scale_armor = Item.objects.create(
        name='Dragon Scale Armor',
        item_type='Equipment',
        description='Exceptional protection crafted from dragon scales.',
        defense=20,
    )
    flameforged_sword = Item.objects.create(
        name='Flameforged Sword',
        item_type='Weapon',
        description='Imbued with dragonfire, cuts through steel.',
        attack_power=10,
    )
    ruby_of_dragon_breath = Item.objects.create(
        name="Ruby of Dragon's Breath",
        item_type='Gem',
        description='Grants fire-based abilities.',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]


