# Generated by Django 5.0.6 on 2024-06-05 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240530_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='has_chest',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='image',
        ),
        migrations.AlterField(
            model_name='tile',
            name='posX',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tile',
            name='posY',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
