# Generated by Django 5.0.6 on 2024-06-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240613_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.world'),
        ),
    ]
