# Generated by Django 5.1.4 on 2025-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250212_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesavedstate',
            name='playable',
            field=models.BooleanField(default=True),
        ),
    ]
