# Generated by Django 5.0.6 on 2024-06-04 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240530_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='has_chest',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/characters/'),
        ),
        migrations.AddField(
            model_name='chest',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/chest/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/items/'),
        ),
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/monsters/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/shop/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/skills/'),
        ),
        migrations.AddField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/worlds/'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/images/tiles/'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='posX',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tile',
            name='posY',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
