# Generated by Django 5.0.6 on 2024-06-05 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tile_has_chest_remove_tile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='power',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
